INSERT INTO DEPARTMENT (ID, DEPT_NAME) VALUES(1000, 'IT');
INSERT INTO DEPARTMENT (ID, DEPT_NAME) VALUES(1001, 'HR');

INSERT INTO EMPLOYEE (ID, DEPT_ID, NAME, SALARY, DESIGNATION) VALUES(100, 1000, 'Asim Khan', 150000, 'Software Engineer');
INSERT INTO EMPLOYEE (ID, DEPT_ID, NAME, SALARY, DESIGNATION) VALUES(101, 1000, 'Anshul Sharma', 250000, 'Team Lead');
INSERT INTO EMPLOYEE (ID, DEPT_ID, NAME, SALARY, DESIGNATION) VALUES(102, 1001, 'Mohit', 200000, 'HR Head');

--INSERT INTO EMPLOYEE (ID, NAME, SALARY, DESIGNATION) VALUES(100,'Asim Khan', 150000, 'Software Engineer');
--INSERT INTO EMPLOYEE (ID, NAME, SALARY, DESIGNATION) VALUES(101,'Anshul Sharma', 250000, 'Team Lead');
--INSERT INTO EMPLOYEE (ID, NAME, SALARY, DESIGNATION) VALUES(102,'Mohit', 200000, 'HR Head');